### ISSUE TITLE
有一个小错误

### ISSUE THREAD

**Issue by LoseSynchronization** [liyifeng/flumeUserGuideCnDoc#1]
![snipaste_20200205_155120](https://user-images.githubusercontent.com/46264163/73821651-6007ad00-482f-11ea-9fd8-e4b7e8935607.png)
在 “在Agent中增加一个流” 这一小节的这一行
`agent_foo.sinks = hdfs-Cluster1-sink1 avro-forward-sink2             # 该agent中有2个sink，分别是：avro-AppSrv-source1 和exec-tail-source2`

**Comment by liyifeng** [comment]
谢谢，反馈已经收到，找时间会修复上去。
